### ISSUE TITLE
problem with sorting, 

### ISSUE THREAD

**Issue by zaiboo786** [ethan626/craigraker#1]
is there anyway to sort the information by date and time, like most recent posts?
also is there anyway to get the email/phone number information? idk how to add the p.class

**Comment by ethan626** [comment]
Craigslist default sorting is by most recently posted so if no option is specified the default sorting should be by time. I will check it out to make sure that is how the data is still being presented as sorting could have changed with the addition of async/await. 

As for the email and phone info, you will need a way to render js such as phantom js.

**Comment by ethan626** [comment]
Added sorting by posting date.

**Comment by zaiboo786** [comment]
thank you but now i cant run the program now
i get this error
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10c7a3e48>
Traceback (most recent call last):
  File "craigraker.py", line 272, in <module>
    results = [result for result,counter in zip(scrape(search_url, args.query, verbose=args.verbose, wanted=args.ignorewanted),
  File "craigraker.py", line 193, in scrape
    max_results = [i.result() if not max_results else max_results for i in completed if i.result()][0] 
IndexError: list index out of range

also could you make it possible to export the data on to an excel sheet?

**Comment by ethan626** [comment]
One can pipe the program output to a file and open that file in an excel sheet. 

What options are you calling the program with?

I believe the cl page is not giving the number of search results, so perhaps there are none? 
This should probably be put in a try/except block in the case that there are no search results.

**Comment by ethan626** [comment]
Added try/except blocks to catch that error.

**Comment by zaiboo786** [comment]
i ran the script, i think theres a problem with getting the most recent posting. it gets the date when the post was "updated" date, is it possible to get it to the "posted" date? 

Also im trying to run a way to make an excel file and i do not know how to make it work. I am new to python scripting and i am trying to learn and understand how things work together. any way you could show me an file output command that can also sort the categories?

i found another project similar to yours, i was wondering if you could look at it and help me figure out how it works as a whole?

**Comment by ethan626** [comment]
I think the date posted could be put into the verbose option easily. Or perhaps as its own separate option - next commit. 

To make an excel file, pipe the program output to a file using the shell and open that file with excel.

craigraker -options >> file.csv   
then
excel file.csv

**Comment by zaiboo786** [comment]
okay thank i got it to work perfectly.
hey do you think i could get your email info?
i think i found a way to view the 'show contact info' and see the email or phone number.

**Comment by ethan626** [comment]
I just looked at the source closely. Looks like you can just follow the link and grab it from there. Is that your solution?

**Comment by zaiboo786** [comment]
Yea do you think it'll work ? 
I just sent you an email

**Comment by ethan626** [comment]
It works I actually ended up adding it to the scraper.
