### ISSUE TITLE
could you add an export option as well? 

### ISSUE THREAD

**Issue by zaiboo786** [ethan626/craigraker#3]
could you add an export option as well?  like in a .cvs excel file format? or push it to a google sheet/drive account?

**Comment by ethan626** [comment]
For a csv file, one can just pipe it with the shell, for example with bash; craigraker [opts] >> file.csv

 Do you think there needs to be an explicit export option? 

The google sheet idea is an interesting suggestion, could be useful addition.

**Comment by zaiboo786** [comment]
thank you i got it to work :)
